spring:
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: none
        properties:
            dialect: org.hibernate.dialect.MySQL8Dialect
            hibernate:
                format_sql: true
        open-in-view: false
    datasource:
        url: ${DATASOURCE_URL:jdbc:mysql://localhost:3307/template?createDatabaseIfNotExist=true}
        password: ${DATASOURCE_PASSWORD:P@ssw0rd}
        username: ${DATASOURCE_USERNAME:root}
