spring:
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
        open-in-view: false
    datasource:
        url: ${DATASOURCE_URL:jdbc:mysql://localhost:3309/yapp22?createDatabaseIfNotExist=true}
        password: ${DATASOURCE_PASSWORD:P@ssw0rd}
        username: ${DATASOURCE_USERNAME:root}




