spring:
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
        open-in-view: false
    datasource:
        url: jdbc:mysql://152.67.210.48:3306/temp?createDatabaseIfNotExist=true
        password: ${DATASOURCE_PASSWORD:bricklog1q2w3e4rls}
        username: ${DATASOURCE_USERNAME:root}




