spring:
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: d3a696681afc2a439388ab9851e0cff2
                        client-secret: NZftWutTIX7OgeEGJbGjKn9cbxrhpPkQ
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: POST
                        client-name: Kakao
                        scope:
                            - account_email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
    auth:
        tokenExpiry: 1800000
        refreshTokenExpiry: 604800000
    oauth2:
        authorizedRedirectUris:
            - http://localhost:3000/oauth/redirect
