server:
    tomcat:
      mbeanregistry:
          enabled: true
management:
  endpoints:
      web:
          base-path: /monitoring
          exposure:
              include:
                  - health
                  - metrics




