spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: local
  config:
    import:
      - application-actuator.yml
      - application-client-${spring.profiles.active}.yml
      - application-storage-${spring.profiles.active}.yml
springdoc:
  swagger-ui:
    path: /swagger
